version: '3'
services:
  bot:
    build: '.'
    restart: unless-stopped
    env_file:
      - .env
      - .env.secret
    volumes:
      - ./data:/app/data
  bot_dev:
    build:
      context: '.'
      dockerfile: Dockerfile.dev
    profiles: [ "dev" ] # only runs with dev profile
    env_file:
      - .env
      - .env.secret
    volumes:
      - ./:/app
