# syntax=docker/dockerfile:1

FROM python:3.10-slim-buster

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

#ENV PYTHONPATH=$PYTHONPATH, ../src, ../src/lib
COPY . .

CMD [ "python3", "-m", "pytest"]